services:
  arc-ai:
    container_name: arc-ai
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5000:5000"

    volumes:
      - ./.whatsapp-sessions:/app/.whatsapp-sessions

